#!/usr/bin/env python3
"""Generates CURLcode, CURLOPT, CURLINFO, and CURLMOPT enums from local curl
submodule headers and generates sourcepawn/async2/curl_enums.inc.

The approach:
  1. Run the C preprocessor on the headers to strip comments and expand macros
  2. Extract enum member names from the clean preprocessed text
  3. Generate a C program that printf's each name and its value
  4. Compile against the local headers (no -lcurl linking needed — enum
     values are compile-time constants)
  5. Run the binary and write the full curl_enums.inc file

Usage: python3 tools/gen_enums.py
"""

import os
import re
import subprocess
import sys
import tempfile

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CURL_INCLUDE = os.path.join(ROOT_DIR, 'third_party', 'curl', 'include')
CURL_H = os.path.join(CURL_INCLUDE, 'curl', 'curl.h')
MULTI_H = os.path.join(CURL_INCLUDE, 'curl', 'multi.h')
INC_FILE = os.path.join(ROOT_DIR, 'sourcepawn', 'async2', 'curl_enums.inc')


def find_compiler():
    """Return a (compiler, is_msvc) tuple."""
    cc = os.environ.get('CC')
    if cc:
        return cc, False

    if sys.platform == 'win32':
        # Try cl.exe first (MSVC), then cc/gcc as fallback
        for candidate in ['cl', 'gcc', 'cc']:
            try:
                subprocess.run([candidate], capture_output=True)
                return candidate, candidate == 'cl'
            except FileNotFoundError:
                continue
        raise RuntimeError('No C compiler found. Run from a Visual Studio Developer Command Prompt or ensure gcc/cc is on PATH.')

    return 'cc', False


def preprocess(headers):
    """Run the C preprocessor on the given headers and return the output text."""
    compiler, is_msvc = find_compiler()

    with tempfile.NamedTemporaryFile(suffix='.c', mode='w', delete=False) as f:
        for header in headers:
            f.write(f'#include "{header}"\n')
        src = f.name

    try:
        if is_msvc:
            result = subprocess.run(
                ['cl', '/nologo', '/E', f'/I{CURL_INCLUDE}', src],
                capture_output=True, text=True, check=True,
            )
        else:
            result = subprocess.run(
                [compiler, '-E', '-I', CURL_INCLUDE, src],
                capture_output=True, text=True, check=True,
            )
        return result.stdout
    finally:
        os.unlink(src)


def extract_names(text, pattern):
    """Extract enum member names from text using a regex pattern."""
    return re.findall(pattern, text, re.MULTILINE)


def generate_c_source(enum_specs):
    """Build a C source string that prints enum values.

    enum_specs is a list of (enum_name, names_list) tuples.
    """
    lines = [
        '#include <stdio.h>',
        '#include <curl/curl.h>',
        '#include <curl/multi.h>',
        'int main(void) {',
    ]

    for i, (enum_name, names) in enumerate(enum_specs):
        last = (i == len(enum_specs) - 1)
        lines.append(f'    printf("enum {enum_name} {{\\n");')
        for name in names:
            lines.append(f'    printf("    {name} = %d,\\n", (int){name});')
        if last:
            lines.append('    printf("};\\n");')
        else:
            lines.append('    printf("};\\n\\n");')

    lines.append('    return 0;')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def compile_and_run(c_source):
    """Compile the C source and run the resulting binary, returning stdout."""
    compiler, is_msvc = find_compiler()

    with tempfile.TemporaryDirectory(prefix='gen_enums_') as tmpdir:
        src_path = os.path.join(tmpdir, 'gen_enums.c')
        with open(src_path, 'w') as f:
            f.write(c_source)

        if is_msvc:
            bin_path = os.path.join(tmpdir, 'gen_enums.exe')
            subprocess.run(
                ['cl', '/nologo', f'/I{CURL_INCLUDE}', src_path, f'/Fe{bin_path}'],
                check=True, cwd=tmpdir,
            )
        else:
            bin_path = os.path.join(tmpdir, 'gen_enums')
            subprocess.run(
                [compiler, '-I', CURL_INCLUDE, '-o', bin_path, src_path],
                check=True,
            )

        result = subprocess.run([bin_path], capture_output=True, text=True, check=True)
        return result.stdout


def write_inc(enums):
    """Write the full curl_enums.inc file."""
    with open(INC_FILE, 'w') as f:
        f.write('#if defined _async2_curl_enums_included\n')
        f.write('    #endinput\n')
        f.write('#endif\n')
        f.write('#define _async2_curl_enums_included\n')
        f.write('\n')
        f.write('// Auto-generated by tools/gen_enums.py — do not edit manually\n')
        f.write('\n')
        f.write(enums)
        if not enums.endswith('\n'):
            f.write('\n')


def main():
    preprocessed = preprocess([CURL_H, MULTI_H])

    # CURLcode — CURLE_FOO entries, skip CURLE_OBSOLETE* and CURL_LAST
    curlcode_names = extract_names(
        preprocessed,
        r'^\s+(CURLE_(?!OBSOLETE)\w+)\s*[=,]',
    )

    # CURLINFO — CURLINFO_FOO = 0xNNNNNN + N (type tag is a hex constant),
    # skip CURLINFO_LASTONE sentinel
    curlinfo_names = extract_names(
        preprocessed,
        r'^\s+(CURLINFO_\w+)\s*=\s*0x',
    )

    # CURLOPT — CURLOPT_FOO = N + N, skip FUNCTIONPOINT (20000 + N)
    # and CURLOPT_LASTENTRY sentinel (no '=' on that line).
    # Extract (name, value) pairs and filter by type prefix to avoid
    # regex backtracking issues with negative lookaheads.
    curlopt_pairs = re.findall(
        r'^\s+(CURLOPT_\w+)\s*=\s*(.+)',
        preprocessed, re.MULTILINE,
    )
    curlopt_names = [n for n, v in curlopt_pairs if not v.startswith('20000')]

    # CURLMOPT — CURLMOPT_FOO = N + N, skip FUNCTIONPOINT (20000 + N)
    # and OBJECTPOINT (10000 + N) and CURLMOPT_LASTENTRY sentinel
    curlmopt_pairs = re.findall(
        r'^\s+(CURLMOPT_\w+)\s*=\s*(.+)',
        preprocessed, re.MULTILINE,
    )
    curlmopt_names = [n for n, v in curlmopt_pairs
                      if not v.startswith(('20000', '10000'))]

    c_source = generate_c_source([
        ('CURLcode', curlcode_names),
        ('CURLINFO', curlinfo_names),
        ('CURLOPT', curlopt_names),
        ('CURLMOPT', curlmopt_names),
    ])
    enums = compile_and_run(c_source)
    write_inc(enums)
    print(f'Updated {INC_FILE}')


if __name__ == '__main__':
    main()
